
package com.learnwebservices.services.hello;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HelloEndpoint", targetNamespace = "http://learnwebservices.com/services/hello")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HelloEndpoint {


    /**
     * 
     * @param helloRequest
     * @return
     *     returns com.learnwebservices.services.hello.HelloResponse
     */
    @WebMethod(operationName = "SayHello")
    @WebResult(name = "HelloResponse", targetNamespace = "http://learnwebservices.com/services/hello", partName = "HelloResponse")
    public HelloResponse sayHello(
        @WebParam(name = "HelloRequest", targetNamespace = "http://learnwebservices.com/services/hello", partName = "HelloRequest")
        HelloRequest helloRequest);

}
